add_newline = false
scan_timeout = 1000

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[python]
detect_extensions = []
detect_files = []

[nodejs]
detect_files = ["package.json"]
