local set_opt = vim.opt
set_opt.expandtab = true
set_opt.confirm = true
set_opt.smartindent = true
set_opt.number = true
set_opt.relativenumber = true
set_opt.foldenable = true
set_opt.exrc = true
set_opt.errorbells = false
set_opt.encoding = "utf-8"
set_opt.incsearch = true
set_opt.hidden = true
set_opt.backup = false
set_opt.clipboard = "unnamedplus"
set_opt.cmdheight = 2
set_opt.cursorline = true
set_opt.completeopt = { "menuone", "noinsert", "noselect" }
set_opt.mouse = "a"
set_opt.background = "dark"
set_opt.termguicolors = true
set_opt.tabstop = 4
set_opt.shiftwidth = 4
set_opt.softtabstop = 4
set_opt.swapfile = false
set_opt.smartcase = true
set_opt.title = true
set_opt.wildmenu = true
