vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "[N]o highlight search" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "[E]xit terminal mode" })
vim.keymap.set("n", "<leader>vt", function()
	vim.cmd("vsplit | term")
end, { desc = "[O]pens a vertical split terminal" })
vim.keymap.set("n", "<leader>ht", function()
	vim.cmd("split | term")
end, { desc = "[O]pens a horizontal split terminal" })
